INSERT INTO STUDENTS(STUDENT_ID, NAME, LAST_NAME, COURSE, ADDRESS_ID) VALUES(1, 'Zenon', 'Baleron', 'plazing', 1);
INSERT INTO STUDENTS(STUDENT_ID, NAME, LAST_NAME, COURSE, ADDRESS_ID) VALUES(2, 'Azja', 'Tuhajbejowicz', 'dendrologia', 2);
INSERT INTO STUDENTS(STUDENT_ID, NAME, LAST_NAME, COURSE, ADDRESS_ID) VALUES(3, 'Arek', 'Zegarek', 'zegarmistrzostwo', 3);
INSERT INTO ADDRESSES(ADDRESS_ID, POST_CODE, CITY, STREET, BUILDING_NUMBER) VALUES(1, '69-666', 'Placeholder City', 'Placeholder Street', '69');
INSERT INTO ADDRESSES(ADDRESS_ID, POST_CODE, CITY, STREET, BUILDING_NUMBER) VALUES(2, '69-666', 'Placeholder City', 'Placeholder Street', '69A');
INSERT INTO ADDRESSES(ADDRESS_ID, POST_CODE, CITY, STREET, BUILDING_NUMBER) VALUES(3, '69-666', 'Placeholder City', 'Placeholder Street', '69B');