CREATE SEQUENCE STUDENTS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADDRESSES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE STUDENTS (
    STUDENT_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    COURSE VARCHAR(255),
    ADDRESS_ID INTEGER
);

CREATE TABLE ADDRESSES (
    ADDRESS_ID INTEGER PRIMARY KEY,
    POST_CODE VARCHAR(10),
    CITY VARCHAR(255),
    STREET VARCHAR(255),
    BUILDING_NUMBER VARCHAR(20)
);
