CREATE SEQUENCE STUDENTS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE STUDENTS (
    STUDENT_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    COURSE VARCHAR(255)
);
